### ISSUE TITLE
Missing VOCAB file

### ISSUE THREAD

**Issue by gsoykan** [miyyer/comics#7]
Could you please provide vocab file necessary for text data?
`vdict, rvdict = pickle.load(open('data/comics_vocab.p', 'rb'))`

**Comment by emanuelevivoli** [comment]
Hello, I had the same problem but I just discovered that you can create the file both by using `setup.sh` or (once you have all the files) by running `python create_hdf5.py`.

Hope it helped

**Comment by gsoykan** [comment]
yes, i did that too, but thank you for indicating it here, so that everyone will use this information :)
